spring.application.name=digitalwallet

# Direct Connection Setup
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${SUPABASE_USERNAME}
spring.datasource.password=${SUPABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

supabase.url=${SUPABASE_URL}
supabase.service-key=${SUPABASE_SERVICEKEY}
supabase.bucket.kyc=${KYC_BUCKET}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}

# HikariCP Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.data-source-properties.prepareThreshold=0


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

server.servlet.context-path=/api

jwt.secret=${JWT_SECRET}

# Global Wallet Configuration
wallet.default-daily-limit=50000


# Spring Mail Configuration (Gmail SMTP example)
spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Local storage base folder
file.upload-dir=uploads

# Spring multipart file limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Tesseract OCR Installation Configuration
tesseract.datapath=${TESSERACT_DATAPATH}
tesseract.language=eng+nep
