spring.application.name=digitalwallet

spring.datasource.url=jdbc:postgresql://localhost:5432/[DBNAME]
spring.datasource.username=postgres
spring.datasource.password=****
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

server.servlet.context-path=/api

# Global Wallet Configuration
wallet.default-daily-limit=50000.00

twilio.account.sid=YOUR_ACCOUNT_SID
twilio.auth.token=YOUR_AUTH_TOKEN
twilio.phone.number=YOUR_TWILIO_PHONE_NUMBER

jwt.secret=
jwt.expiration=3600000

# Spring Mail Configuration (Gmail SMTP example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Local storage base folder
file.upload-dir=uploads

# Spring multipart file limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Tesseract OCR Installation Configuration
tesseract.datapath=D:/OCR/tessdata
tesseract.language=eng+nep
