package com.project.digitalwallet.common.enums;

public enum NotificationType {
    TRANSACTION_CREDIT,
    TRANSACTION_DEBIT,
    SECURITY_ALERT,
    WELCOME,
    KYC_VERIFIED,
    KYC_REJECTED,
    MONEY_REQUEST_RECEIVED,
    MONEY_REQUEST_ACCEPTED,
    MONEY_REQUEST_DECLINED,
    MONEY_REQUEST_CANCELLED
}